import type { Metadata } from "next";
import { DocumentProvider } from "@/context/DocumentContext";
import { supabase } from "@/lib/supabase";
import "./globals.css";
import { Noto_Sans_JP } from 'next/font/google'

const notoSansJp = Noto_Sans_JP({
  subsets: ['latin'],
  preload: false,
  variable: '--font-noto-sans-jp',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  // 🔹 サーバーコンポーネント内で Supabase からデータを取得
  const { data, error } = await supabase.from("documents").select("*").single();

  return (
    <html lang="ja">
      <body className={notoSansJp.variable}>
        <DocumentProvider initialData={data || null} error={error?.message || null}>
          {children}
        </DocumentProvider>
      </body>
    </html>
  );
}
