import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Sidebar from "@/components/ui/Sidebar";
import { DocumentProvider } from "@/context/DocumentContext";
import { supabase } from "@/lib/supabase";
import "./globals.css";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  // 🔹 サーバーコンポーネント内で Supabase からデータを取得
  const { data, error } = await supabase.from("documents").select("*").single();

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <DocumentProvider initialData={data || null} error={error?.message || null}>
          {children}
        </DocumentProvider>
      </body>
    </html>
  );
}
